name: Build
on: 
  push:
    branches: ['*']
    tags: ['*']

permissions:
  contents: write   # needed to create GitHub Releases
  packages: write   # needed to push images to GHCR

jobs:
  publish:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: metax-sensors/musl-build-image  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  extract-toolchain:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Extract toolchain
        run: |
          docker pull ghcr.io/metax-sensors/musl-build-image:latest
          docker run --rm -v $(pwd):/data ghcr.io/metax-sensors/musl-build-image:latest \
            /bin/tar -czvf /data/arm-bemos-linux-musleabihf.tar.gz /opt/x-tools/arm-bemos-linux-musleabihf/
      - name: Archive toolchain
        uses: actions/upload-artifact@v7
        with:
          name: toolchain archive
          path: arm-bemos-linux-musleabihf.tar.gz
  
  create-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: extract-toolchain
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: toolchain archive
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Rename artifact
        run: mv arm-bemos-linux-musleabihf.tar.gz arm-bemos-linux-musleabihf_${{ github.ref_name }}.tar.gz
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Create matching container tag
        run: |
          IMAGE=ghcr.io/metax-sensors/musl-build-image
          docker pull ${IMAGE}:latest
          docker tag ${IMAGE}:latest ${IMAGE}:${{ github.ref_name }}
          docker push ${IMAGE}:${{ github.ref_name }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: Automatically created
          files: arm-bemos-linux-musleabihf_${{ github.ref_name }}.tar.gz